### ISSUE TITLE
Change in artifact name - Gren no longer creates release notes!

### ISSUE THREAD

**Issue by tomshercliff** [github-tools/github-release-notes#162]
We have recently changed the artifact name in the pom of one of our projects, and since then Gren doesn't seem to find new released versions to generate release notes when running 'gren release' (it only finds the previous two versions before the name change occurred - which have already had release notes generated!).

The tag created by maven release:prepare is visible in Github, and release notes can be added manually which I assume would make them into a Release as far as Github is concerned?

Incidentally, running 'gren release —tags=all' did generate notes for all versions, including the new ones since the name change.

How does gren identify the last two releases in github to generate the last two release notes?

Thanks!

**Comment by alexcanessa** [comment]
Hello @tomshercliff,

It might be a problem related to #134. Could you tell me the names of the tags that `gren` doesn't pick up and the ones that does pick up?

**Comment by tomshercliff** [comment]
Hi @alexcanessa - the names of the tags which are picked up are below:
chronicle-fix-parent-1.5.16
chronicle-fix-parent-1.5.17

Then we changed the artifactId in the pom from chronicle-fix-parent to chronicle-fix, and the tags below were not picked up:
chronicle-fix-1.5.18
chronicle-fix-1.5.19
etc.

So are you suggesting that (relating to #134) because chronicle-fix-1.5.18 will be sorted alphabetically *before* chronicle-fix-parent-1.5.17, this is causing Gren to still view chronicle-fix-parent-1.5.16 and chronicle-fix-parent-1.5.17 as the 2 latest ones and hence only generate notes for 1.5.17?

**Comment by alexcanessa** [comment]
@tomshercliff yep something like that.

A release is going to get out soon and should fix this.
I'll update this issue 👍

**Comment by RobAustin** [comment]
@alexcanessa  thanks

**Comment by tomshercliff** [comment]
Hi @alexcanessa - has this issue been fixed?  Thanks!

**Comment by alexcanessa** [comment]
It should be fixed by [0.16.0](https://github.com/github-tools/github-release-notes/releases/tag/0.16.0).

Could you check if you still have a problem?

**Comment by tomshercliff** [comment]
Hi @alexcanessa - seems like we still have an issue here.  It still seems to be trying to access the latest release when the release names are sorted alphabetically:

[09:25:27][Step 2/2] Running command: [/usr/bin/gren, release] in /home/teamcity/agent_chronicle3/agent/3/work/84985a4243a311c4/ReleaseAutomation/projects/Chronicle-FIX
[09:25:28][Step 2/2] 
[09:25:28][Step 2/2]     - Generate release notes:
[09:25:28][Step 2/2] ===================================
[09:25:31][Step 2/2] { Error: 422 error making request POST https://api.github.com/repos/ChronicleEnterprise/Chronicle-FIX/releases: "Unprocessable Entity"
[09:25:31][Step 2/2]     at new ResponseError (/usr/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:50:118)
[09:25:31][Step 2/2]     at handler (/usr/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:373:18)
[09:25:31][Step 2/2]     at <anonymous>
[09:25:31][Step 2/2]     at process._tickCallback (internal/process/next_tick.js:188:7)
[09:25:31][Step 2/2]   path: '/repos/ChronicleEnterprise/Chronicle-FIX/releases',
[09:25:31][Step 2/2]   request: 
[09:25:31][Step 2/2]    { adapter: [Function: httpAdapter],
[09:25:31][Step 2/2]      transformRequest: { '0': [Function: transformRequest] },
[09:25:31][Step 2/2]      transformResponse: { '0': [Function: transformResponse] },
[09:25:31][Step 2/2]      timeout: 0,
[09:25:31][Step 2/2]      xsrfCookieName: 'XSRF-TOKEN',
[09:25:31][Step 2/2]      xsrfHeaderName: 'X-XSRF-TOKEN',
[09:25:31][Step 2/2]      maxContentLength: -1,
[09:25:31][Step 2/2]      validateStatus: [Function: validateStatus],
[09:25:31][Step 2/2]      headers: 
[09:25:31][Step 2/2]       { Accept: 'application/vnd.github.v3+json',
[09:25:31][Step 2/2]         'Content-Type': 'application/json;charset=UTF-8',
[09:25:31][Step 2/2]         Authorization: 'token dcad189a331b3561cfa6fc652c13b82a7ed713c2',
[09:25:31][Step 2/2]         'User-Agent': 'axios/0.15.3',
[09:25:31][Step 2/2]         'Content-Length': 249 },
[09:25:31][Step 2/2]      method: 'POST',
[09:25:31][Step 2/2]      url: 'https://api.github.com/repos/ChronicleEnterprise/Chronicle-FIX/releases',
[09:25:31][Step 2/2]      params: {},
[09:25:31][Step 2/2]      data: '{"tag_name":"chronicle-fix-parent-1.5.17","name":"chronicle-fix-parent-1.5.17","body":"- [**closed**] Apply back pressure to FixSessionHandler.sendMessage [#172](https://github.com/ChronicleEnterprise/Chronicle-FIX/issues/172)\\n","prerelease":false}',
[09:25:31][Step 2/2]      responseType: 'json' },
[09:25:31][Step 2/2]   response: 
[09:25:31][Step 2/2]    { status: 422,
[09:25:31][Step 2/2]      statusText: 'Unprocessable Entity',
[09:25:31][Step 2/2]      headers: 
[09:25:31][Step 2/2]       { server: 'GitHub.com',
[09:25:31][Step 2/2]         date: 'Thu, 31 May 2018 08:25:31 GMT',
[09:25:31][Step 2/2]         'content-type': 'application/json; charset=utf-8',
[09:25:31][Step 2/2]         'content-length': '195',
[09:25:31][Step 2/2]         connection: 'close',
[09:25:31][Step 2/2]         status: '422 Unprocessable Entity',
[09:25:31][Step 2/2]         'x-ratelimit-limit': '5000',
[09:25:31][Step 2/2]         'x-ratelimit-remaining': '4925',
[09:25:31][Step 2/2]         'x-ratelimit-reset': '1527757055',
[09:25:31][Step 2/2]         'x-oauth-scopes': 'gist, notifications, repo, user',
[09:25:31][Step 2/2]         'x-accepted-oauth-scopes': 'repo',
[09:25:31][Step 2/2]         'x-github-media-type': 'github.v3; format=json',
[09:25:31][Step 2/2]         'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
[09:25:31][Step 2/2]         'access-control-allow-origin': '*',
[09:25:31][Step 2/2]         'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
[09:25:31][Step 2/2]         'x-frame-options': 'deny',
[09:25:31][Step 2/2]         'x-content-type-options': 'nosniff',
[09:25:31][Step 2/2]         'x-xss-protection': '1; mode=block',
[09:25:31][Step 2/2]         'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
[09:25:31][Step 2/2]         'content-security-policy': 'default-src \'none\'',
[09:25:31][Step 2/2]         'x-runtime-rack': '0.052773',
[09:25:31][Step 2/2]         'x-github-request-id': 'EBFC:0268:21CDA9C:52BCA56:5B0FB17B' },
[09:25:31][Step 2/2]      config: 
[09:25:31][Step 2/2]       { adapter: [Function: httpAdapter],
[09:25:31][Step 2/2]         transformRequest: [Object],
[09:25:31][Step 2/2]         transformResponse: [Object],
[09:25:31][Step 2/2]         timeout: 0,
[09:25:31][Step 2/2]         xsrfCookieName: 'XSRF-TOKEN',
[09:25:31][Step 2/2]         xsrfHeaderName: 'X-XSRF-TOKEN',
[09:25:31][Step 2/2]         maxContentLength: -1,
[09:25:31][Step 2/2]         validateStatus: [Function: validateStatus],
[09:25:31][Step 2/2]         headers: [Object],
[09:25:31][Step 2/2]         method: 'POST',
[09:25:31][Step 2/2]         url: 'https://api.github.com/repos/ChronicleEnterprise/Chronicle-FIX/releases',
[09:25:31][Step 2/2]         params: {},
[09:25:31][Step 2/2]         data: '{"tag_name":"chronicle-fix-parent-1.5.17","name":"chronicle-fix-parent-1.5.17","body":"- [**closed**] Apply back pressure to FixSessionHandler.sendMessage [#172](https://github.com/ChronicleEnterprise/Chronicle-FIX/issues/172)\\n","prerelease":false}',
[09:25:31][Step 2/2]         responseType: 'json' },
[09:25:31][Step 2/2]      request: 
[09:25:31][Step 2/2]       Writable {
[09:25:31][Step 2/2]         _writableState: [Object],
[09:25:31][Step 2/2]         writable: true,
[09:25:31][Step 2/2]         domain: null,
[09:25:31][Step 2/2]         _events: [Object],
[09:25:31][Step 2/2]         _eventsCount: 2,
[09:25:31][Step 2/2]         _maxListeners: undefined,
[09:25:31][Step 2/2]         _options: [Object],
[09:25:31][Step 2/2]         _redirectCount: 0,
[09:25:31][Step 2/2]         _onNativeResponse: [Function],
[09:25:31][Step 2/2]         _currentRequest: [Object],
[09:25:31][Step 2/2]         _currentUrl: 'https://api.github.com' },
[09:25:31][Step 2/2]      data: 
[09:25:31][Step 2/2]       { message: 'Validation Failed',
[09:25:31][Step 2/2]         errors: [Array],
[09:25:31][Step 2/2]         documentation_url: 'https://developer.github.com/v3/repos/releases/#create-a-release' } },
[09:25:31][Step 2/2]   status: undefined }
[09:25:31][Step 2/2] Failed to get release notes for CHRONICLE_FIX-1.16.0:
[09:25:31][Step 2/2] gren command exited with code 1

Any thoughts on this?

**Comment by alexcanessa** [comment]
This should be fixed by 2460facf950c3351a6cd7f642ffac10f4b965388
